CREATE TYPE "InventoryItemNature" AS ENUM ('STOCK','NON_STOCK','SERVICE','RAW_MATERIAL','WIP','FINISHED_GOOD','CONSUMABLE','ASSET');
CREATE TYPE "BatchAllocationStrategy" AS ENUM ('FIFO','FEFO','MANUAL');
CREATE TYPE "WarehouseStockType" AS ENUM ('STORES','WIP','FINISHED_GOODS','QC_HOLD','REJECTED','SCRAP','GOODS_IN_TRANSIT','SUPPLIER_JOB_WORKER');
CREATE TYPE "StockReconciliationStatus" AS ENUM ('DRAFT','COUNTING','PENDING_APPROVAL','APPROVED','SUBMITTED','CANCELLED');
CREATE TYPE "StockTransferStatus" AS ENUM ('DRAFT','SUBMITTED','DISPATCHED','IN_TRANSIT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED');
ALTER TYPE "StockEntryPurpose" ADD VALUE 'MANUFACTURE'; ALTER TYPE "StockEntryPurpose" ADD VALUE 'SCRAP'; ALTER TYPE "StockEntryPurpose" ADD VALUE 'CUSTOMER_RETURN'; ALTER TYPE "StockEntryPurpose" ADD VALUE 'SUPPLIER_RETURN'; ALTER TYPE "StockEntryPurpose" ADD VALUE 'JOB_WORK_ISSUE'; ALTER TYPE "StockEntryPurpose" ADD VALUE 'JOB_WORK_RECEIPT';

ALTER TABLE "Batch" ADD COLUMN "supplierBatchNo" TEXT, ADD COLUMN "supplierId" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN "demandReference" TEXT, ADD COLUMN "sourceDocumentId" TEXT, ADD COLUMN "sourceDocumentType" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN "fulfilledQty" DECIMAL(18,6) NOT NULL DEFAULT 0, ADD COLUMN "issuedQty" DECIMAL(18,6) NOT NULL DEFAULT 0, ADD COLUMN "manufacturedQty" DECIMAL(18,6) NOT NULL DEFAULT 0, ADD COLUMN "purchaseOrderItemId" TEXT, ADD COLUMN "sourceDocumentId" TEXT, ADD COLUMN "sourceDocumentType" TEXT, ADD COLUMN "workOrderId" TEXT;
ALTER TABLE "Product" ADD COLUMN "backflush" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "batchAllocationStrategy" "BatchAllocationStrategy" NOT NULL DEFAULT 'FIFO', ADD COLUMN "cogsAccountId" TEXT, ADD COLUMN "drawingReference" TEXT, ADD COLUMN "finalInspectionRequired" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "inProcessInspectionRequired" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "inventoryAccountId" TEXT, ADD COLUMN "itemNature" "InventoryItemNature" NOT NULL DEFAULT 'STOCK', ADD COLUMN "leadTimeDays" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "minimumOrderQty" DECIMAL(18,6) NOT NULL DEFAULT 0, ADD COLUMN "orderMultiple" DECIMAL(18,6) NOT NULL DEFAULT 1, ADD COLUMN "receiptInspectionRequired" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "revisionReference" TEXT, ADD COLUMN "safetyStock" DECIMAL(18,6) NOT NULL DEFAULT 0, ADD COLUMN "shelfLifeDays" INTEGER, ADD COLUMN "stockAdjustmentAccountId" TEXT;
ALTER TABLE "StockEntry" ADD COLUMN "amendedFromId" TEXT, ADD COLUMN "revisionNo" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "sourceDocumentId" TEXT, ADD COLUMN "sourceDocumentType" TEXT;
ALTER TABLE "StockLedgerEntry" ADD COLUMN "repostVersion" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "reversalOfId" TEXT;
ALTER TABLE "StockLevel" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(18,6) USING "quantity"::DECIMAL(18,6), ALTER COLUMN "reservedQty" SET DATA TYPE DECIMAL(18,6) USING "reservedQty"::DECIMAL(18,6);
ALTER TABLE "StockMovement" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(18,6) USING "quantity"::DECIMAL(18,6), ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(18,6) USING "unitCost"::DECIMAL(18,6);
ALTER TABLE "Warehouse" ADD COLUMN "branchId" UUID, ADD COLUMN "frozenAt" TIMESTAMP(3), ADD COLUMN "frozenById" TEXT, ADD COLUMN "isFrozen" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "locationPath" TEXT, ADD COLUMN "plantId" UUID, ADD COLUMN "stockType" "WarehouseStockType" NOT NULL DEFAULT 'STORES', ADD COLUMN "tenantId" UUID;

CREATE TABLE "ProductWarehouseRule" ("id" TEXT PRIMARY KEY, "companyId" TEXT, "productId" TEXT NOT NULL, "warehouseId" TEXT NOT NULL, "reorderLevel" DECIMAL(18,6) NOT NULL DEFAULT 0, "reorderQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "safetyStock" DECIMAL(18,6) NOT NULL DEFAULT 0, "leadTimeDays" INTEGER NOT NULL DEFAULT 0, "minimumOrderQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "orderMultiple" DECIMAL(18,6) NOT NULL DEFAULT 1, "isDefault" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CustomerItemCode" ("id" TEXT PRIMARY KEY, "companyId" TEXT, "productId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "customerCode" TEXT NOT NULL, "description" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "BatchGenealogy" ("id" TEXT PRIMARY KEY, "companyId" TEXT, "outputBatchId" TEXT NOT NULL, "inputBatchId" TEXT NOT NULL, "outputProductId" TEXT NOT NULL, "inputProductId" TEXT NOT NULL, "quantityUsed" DECIMAL(18,6) NOT NULL, "stockEntryId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "StockReconciliation" ("id" TEXT PRIMARY KEY, "companyId" TEXT, "reconciliationNo" TEXT NOT NULL, "warehouseId" TEXT NOT NULL, "status" "StockReconciliationStatus" NOT NULL DEFAULT 'DRAFT', "blindCount" BOOLEAN NOT NULL DEFAULT false, "snapshotAt" TIMESTAMP(3), "frozenAt" TIMESTAMP(3), "varianceThreshold" DECIMAL(18,6) NOT NULL DEFAULT 0, "approvalInstanceId" UUID, "adjustmentEntryId" TEXT, "notes" TEXT, "countedById" TEXT, "submittedAt" TIMESTAMP(3), "cancelledAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "StockReconciliationItem" ("id" TEXT PRIMARY KEY, "reconciliationId" TEXT NOT NULL, "productId" TEXT NOT NULL, "batchId" TEXT, "serialNoId" TEXT, "bookQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "countedQty" DECIMAL(18,6), "varianceQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "valuationRate" DECIMAL(18,6) NOT NULL DEFAULT 0, "varianceValue" DECIMAL(18,6) NOT NULL DEFAULT 0, "countNotes" TEXT, "countedAt" TIMESTAMP(3));
CREATE TABLE "StockTransferOrder" ("id" TEXT PRIMARY KEY, "companyId" TEXT, "transferNo" TEXT NOT NULL, "status" "StockTransferStatus" NOT NULL DEFAULT 'DRAFT', "sourceWarehouseId" TEXT NOT NULL, "transitWarehouseId" TEXT, "destinationWarehouseId" TEXT NOT NULL, "crossPlant" BOOLEAN NOT NULL DEFAULT false, "transporter" TEXT, "vehicleNo" TEXT, "trackingReference" TEXT, "dispatchEntryId" TEXT, "receiptEntryId" TEXT, "dispatchedAt" TIMESTAMP(3), "receivedAt" TIMESTAMP(3), "cancelledAt" TIMESTAMP(3), "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "StockTransferOrderItem" ("id" TEXT PRIMARY KEY, "transferOrderId" TEXT NOT NULL, "productId" TEXT NOT NULL, "quantity" DECIMAL(18,6) NOT NULL, "dispatchedQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "receivedQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "damagedQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "lostQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "batchId" TEXT, "serialNoId" TEXT, "valuationRate" DECIMAL(18,6) NOT NULL DEFAULT 0);
CREATE TABLE "InventoryWorkOrder" ("id" TEXT PRIMARY KEY, "companyId" TEXT, "workOrderNo" TEXT NOT NULL, "materialRequestId" TEXT, "productId" TEXT NOT NULL, "warehouseId" TEXT, "quantity" DECIMAL(18,6) NOT NULL, "producedQty" DECIMAL(18,6) NOT NULL DEFAULT 0, "requiredBy" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'DRAFT', "sourceDocumentType" TEXT, "sourceDocumentId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);

CREATE UNIQUE INDEX "ProductWarehouseRule_productId_warehouseId_key" ON "ProductWarehouseRule"("productId","warehouseId"); CREATE INDEX "ProductWarehouseRule_companyId_warehouseId_idx" ON "ProductWarehouseRule"("companyId","warehouseId");
CREATE UNIQUE INDEX "CustomerItemCode_customerId_productId_key" ON "CustomerItemCode"("customerId","productId"); CREATE UNIQUE INDEX "CustomerItemCode_customerId_customerCode_key" ON "CustomerItemCode"("customerId","customerCode");
CREATE UNIQUE INDEX "BatchGenealogy_outputBatchId_inputBatchId_stockEntryId_key" ON "BatchGenealogy"("outputBatchId","inputBatchId","stockEntryId"); CREATE INDEX "BatchGenealogy_inputBatchId_idx" ON "BatchGenealogy"("inputBatchId"); CREATE INDEX "BatchGenealogy_outputBatchId_idx" ON "BatchGenealogy"("outputBatchId");
CREATE UNIQUE INDEX "StockReconciliation_reconciliationNo_key" ON "StockReconciliation"("reconciliationNo"); CREATE INDEX "StockReconciliation_companyId_status_createdAt_idx" ON "StockReconciliation"("companyId","status","createdAt"); CREATE INDEX "StockReconciliation_warehouseId_snapshotAt_idx" ON "StockReconciliation"("warehouseId","snapshotAt"); CREATE INDEX "StockReconciliationItem_productId_idx" ON "StockReconciliationItem"("productId"); CREATE UNIQUE INDEX "StockReconciliationItem_reconciliationId_productId_batchId_serialNoId_key" ON "StockReconciliationItem"("reconciliationId","productId","batchId","serialNoId");
CREATE UNIQUE INDEX "StockTransferOrder_transferNo_key" ON "StockTransferOrder"("transferNo"); CREATE INDEX "StockTransferOrder_companyId_status_createdAt_idx" ON "StockTransferOrder"("companyId","status","createdAt"); CREATE INDEX "StockTransferOrder_sourceWarehouseId_destinationWarehouseId_idx" ON "StockTransferOrder"("sourceWarehouseId","destinationWarehouseId"); CREATE INDEX "StockTransferOrderItem_transferOrderId_idx" ON "StockTransferOrderItem"("transferOrderId"); CREATE INDEX "StockTransferOrderItem_productId_idx" ON "StockTransferOrderItem"("productId");
CREATE UNIQUE INDEX "InventoryWorkOrder_workOrderNo_key" ON "InventoryWorkOrder"("workOrderNo"); CREATE INDEX "InventoryWorkOrder_companyId_status_idx" ON "InventoryWorkOrder"("companyId","status"); CREATE INDEX "InventoryWorkOrder_materialRequestId_idx" ON "InventoryWorkOrder"("materialRequestId");

ALTER TABLE "ProductWarehouseRule" ADD CONSTRAINT "ProductWarehouseRule_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ProductWarehouseRule" ADD CONSTRAINT "ProductWarehouseRule_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CustomerItemCode" ADD CONSTRAINT "CustomerItemCode_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StockLedgerEntry" ADD CONSTRAINT "StockLedgerEntry_reversalOfId_fkey" FOREIGN KEY ("reversalOfId") REFERENCES "StockLedgerEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "StockEntry" ADD CONSTRAINT "StockEntry_amendedFromId_fkey" FOREIGN KEY ("amendedFromId") REFERENCES "StockEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BatchGenealogy" ADD CONSTRAINT "BatchGenealogy_outputBatchId_fkey" FOREIGN KEY ("outputBatchId") REFERENCES "Batch"("id"); ALTER TABLE "BatchGenealogy" ADD CONSTRAINT "BatchGenealogy_inputBatchId_fkey" FOREIGN KEY ("inputBatchId") REFERENCES "Batch"("id"); ALTER TABLE "BatchGenealogy" ADD CONSTRAINT "BatchGenealogy_outputProductId_fkey" FOREIGN KEY ("outputProductId") REFERENCES "Product"("id"); ALTER TABLE "BatchGenealogy" ADD CONSTRAINT "BatchGenealogy_inputProductId_fkey" FOREIGN KEY ("inputProductId") REFERENCES "Product"("id");
ALTER TABLE "StockReconciliation" ADD CONSTRAINT "StockReconciliation_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id"); ALTER TABLE "StockReconciliationItem" ADD CONSTRAINT "StockReconciliationItem_reconciliationId_fkey" FOREIGN KEY ("reconciliationId") REFERENCES "StockReconciliation"("id") ON DELETE CASCADE;
ALTER TABLE "StockTransferOrder" ADD CONSTRAINT "StockTransferOrder_sourceWarehouseId_fkey" FOREIGN KEY ("sourceWarehouseId") REFERENCES "Warehouse"("id"); ALTER TABLE "StockTransferOrder" ADD CONSTRAINT "StockTransferOrder_transitWarehouseId_fkey" FOREIGN KEY ("transitWarehouseId") REFERENCES "Warehouse"("id") ON DELETE SET NULL; ALTER TABLE "StockTransferOrder" ADD CONSTRAINT "StockTransferOrder_destinationWarehouseId_fkey" FOREIGN KEY ("destinationWarehouseId") REFERENCES "Warehouse"("id"); ALTER TABLE "StockTransferOrderItem" ADD CONSTRAINT "StockTransferOrderItem_transferOrderId_fkey" FOREIGN KEY ("transferOrderId") REFERENCES "StockTransferOrder"("id") ON DELETE CASCADE;

-- Quantitative and identity fields of posted ledger rows are database-immutable.
CREATE FUNCTION prevent_stock_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Stock ledger rows are immutable; post a reversal'; END IF; IF ROW(NEW."productId",NEW."warehouseId",NEW."postingDate",NEW."voucherType",NEW."voucherId",NEW."voucherNo",NEW."actualQty",NEW."qtyAfterTransaction",NEW."valuationRate",NEW."stockValue",NEW."stockValueDifference",NEW."batchId",NEW."serialNoId",NEW."reversalOfId") IS DISTINCT FROM ROW(OLD."productId",OLD."warehouseId",OLD."postingDate",OLD."voucherType",OLD."voucherId",OLD."voucherNo",OLD."actualQty",OLD."qtyAfterTransaction",OLD."valuationRate",OLD."stockValue",OLD."stockValueDifference",OLD."batchId",OLD."serialNoId",OLD."reversalOfId") THEN RAISE EXCEPTION 'Stock ledger quantitative fields are immutable; post a reversal'; END IF; RETURN NEW; END $$;
CREATE TRIGGER stock_ledger_immutable BEFORE UPDATE OR DELETE ON "StockLedgerEntry" FOR EACH ROW EXECUTE FUNCTION prevent_stock_ledger_mutation();
