ALTER TYPE "SalesEnquiryStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "SalesEnquiryStatus" ADD VALUE IF NOT EXISTS 'QUALIFIED';
ALTER TYPE "SalesEnquiryStatus" ADD VALUE IF NOT EXISTS 'QUOTING';
ALTER TYPE "SalesEnquiryStatus" ADD VALUE IF NOT EXISTS 'NEGOTIATION';
ALTER TYPE "SalesEnquiryStatus" ADD VALUE IF NOT EXISTS 'WON';
ALTER TYPE "SalesEnquiryStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
