ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "FiscalYear" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "NumberingSeries" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "StockLevel" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "StockMovement" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "StockLedgerEntry" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "InventoryValuationLayer" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "StockReservation" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "StockEntry" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Batch" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "SerialNumber" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "PriceList" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "ItemPrice" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "PricingRule" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Department" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Position" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "SalesOrder" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "SalesInvoice" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "DeliveryNote" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "TaxTemplate" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Payment" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "PaymentEntry" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "CreditNote" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "GeneralLedgerEntry" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "Budget" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "BankStatementLine" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "PrintFormat" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "SubscriptionTemplate" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "companyId" TEXT;
ALTER TABLE "PurchaseInvoice" ADD COLUMN IF NOT EXISTS "companyId" TEXT;

CREATE INDEX IF NOT EXISTS "Account_companyId_idx" ON "Account"("companyId");
CREATE INDEX IF NOT EXISTS "FiscalYear_companyId_idx" ON "FiscalYear"("companyId");
CREATE INDEX IF NOT EXISTS "JournalEntry_companyId_idx" ON "JournalEntry"("companyId");
CREATE INDEX IF NOT EXISTS "NumberingSeries_companyId_idx" ON "NumberingSeries"("companyId");
CREATE INDEX IF NOT EXISTS "Category_companyId_idx" ON "Category"("companyId");
CREATE INDEX IF NOT EXISTS "Unit_companyId_idx" ON "Unit"("companyId");
CREATE INDEX IF NOT EXISTS "Product_companyId_idx" ON "Product"("companyId");
CREATE INDEX IF NOT EXISTS "StockLevel_companyId_idx" ON "StockLevel"("companyId");
CREATE INDEX IF NOT EXISTS "StockMovement_companyId_idx" ON "StockMovement"("companyId");
CREATE INDEX IF NOT EXISTS "StockLedgerEntry_companyId_idx" ON "StockLedgerEntry"("companyId");
CREATE INDEX IF NOT EXISTS "InventoryValuationLayer_companyId_idx" ON "InventoryValuationLayer"("companyId");
CREATE INDEX IF NOT EXISTS "StockReservation_companyId_idx" ON "StockReservation"("companyId");
CREATE INDEX IF NOT EXISTS "StockEntry_companyId_idx" ON "StockEntry"("companyId");
CREATE INDEX IF NOT EXISTS "Batch_companyId_idx" ON "Batch"("companyId");
CREATE INDEX IF NOT EXISTS "SerialNumber_companyId_idx" ON "SerialNumber"("companyId");
CREATE INDEX IF NOT EXISTS "PriceList_companyId_idx" ON "PriceList"("companyId");
CREATE INDEX IF NOT EXISTS "ItemPrice_companyId_idx" ON "ItemPrice"("companyId");
CREATE INDEX IF NOT EXISTS "PricingRule_companyId_idx" ON "PricingRule"("companyId");
CREATE INDEX IF NOT EXISTS "Department_companyId_idx" ON "Department"("companyId");
CREATE INDEX IF NOT EXISTS "Position_companyId_idx" ON "Position"("companyId");
CREATE INDEX IF NOT EXISTS "Customer_companyId_idx" ON "Customer"("companyId");
CREATE INDEX IF NOT EXISTS "Supplier_companyId_idx" ON "Supplier"("companyId");
CREATE INDEX IF NOT EXISTS "Quotation_companyId_idx" ON "Quotation"("companyId");
CREATE INDEX IF NOT EXISTS "SalesOrder_companyId_idx" ON "SalesOrder"("companyId");
CREATE INDEX IF NOT EXISTS "SalesInvoice_companyId_idx" ON "SalesInvoice"("companyId");
CREATE INDEX IF NOT EXISTS "DeliveryNote_companyId_idx" ON "DeliveryNote"("companyId");
CREATE INDEX IF NOT EXISTS "TaxTemplate_companyId_idx" ON "TaxTemplate"("companyId");
CREATE INDEX IF NOT EXISTS "Payment_companyId_idx" ON "Payment"("companyId");
CREATE INDEX IF NOT EXISTS "PaymentEntry_companyId_idx" ON "PaymentEntry"("companyId");
CREATE INDEX IF NOT EXISTS "CreditNote_companyId_idx" ON "CreditNote"("companyId");
CREATE INDEX IF NOT EXISTS "GeneralLedgerEntry_companyId_idx" ON "GeneralLedgerEntry"("companyId");
CREATE INDEX IF NOT EXISTS "Budget_companyId_idx" ON "Budget"("companyId");
CREATE INDEX IF NOT EXISTS "BankStatementLine_companyId_idx" ON "BankStatementLine"("companyId");
CREATE INDEX IF NOT EXISTS "PrintFormat_companyId_idx" ON "PrintFormat"("companyId");
CREATE INDEX IF NOT EXISTS "SubscriptionTemplate_companyId_idx" ON "SubscriptionTemplate"("companyId");
CREATE INDEX IF NOT EXISTS "AuditLog_companyId_idx" ON "AuditLog"("companyId");
CREATE INDEX IF NOT EXISTS "PurchaseOrder_companyId_idx" ON "PurchaseOrder"("companyId");
CREATE INDEX IF NOT EXISTS "PurchaseInvoice_companyId_idx" ON "PurchaseInvoice"("companyId");
