ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'CUSTOMER';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SUPPLIER';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PAYMENT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'SUPPLIER_PAYMENT';
